name: aws-lambda-function-update

inputs:
  tag:
    required: false
    default: 'main'
  context:
    required: false
    default: '.'
  image:
    required: true
  function_name:
    required: true
  wait_for_update:
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: update lambda function ${{ inputs.function_name }}'s image
      run: |
        aws lambda update-function-code \
          --function-name ${{ inputs.function_name }} \
          --image-uri ${{ inputs.image }}:${{ inputs.tag }}
      shell: bash
    - name: wait lambda function ${{ inputs.function_name }} updated
      if: inputs.wait_for_update == 'true'
      run: |
        aws lambda wait function-updated --function-name ${{ inputs.function_name }}
      shell: bash