name: aws-credentials

inputs:
  aws_region:
    required: false
    default: 'ap-northeast-1'
  role_to_assume:
    required: true

runs:
  using: composite
  steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ inputs.role_to_assume }}
        aws-region: ${{ inputs.aws_region }}
