name: OSV-Scanner Full Scan

on:
  workflow_call:

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  scan-full:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.3.8
